.class Lorg/chromium/network/mojom/NetworkContext_Internal;
.super Ljava/lang/Object;
.source "SourceFile"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetDeviceBoundSessionManagerParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetBoundNetworkForTestingResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetBoundNetworkForTestingResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetBoundNetworkForTestingResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetBoundNetworkForTestingParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextPrefetchParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextExemptUrlFromNetworkRevocationForNonceResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextExemptUrlFromNetworkRevocationForNonceResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextExemptUrlFromNetworkRevocationForNonceResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextExemptUrlFromNetworkRevocationForNonceParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearNoncesParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextRevokeNetworkForNoncesResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextRevokeNetworkForNoncesResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextRevokeNetworkForNoncesResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextRevokeNetworkForNoncesParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextSetCookieDeprecationLabelParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextFlushMatchingCachedClientCertParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextFlushCachedClientCertIfNeededParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextResourceSchedulerClientVisibilityChangedParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextHasPreloadedSharedDictionaryInfoForTestingResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextHasPreloadedSharedDictionaryInfoForTestingResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextHasPreloadedSharedDictionaryInfoForTestingResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextHasPreloadedSharedDictionaryInfoForTestingParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextPreloadSharedDictionaryInfoForDocumentParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextSetSharedDictionaryCacheMaxSizeParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetSharedDictionaryOriginsBetweenResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetSharedDictionaryOriginsBetweenResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetSharedDictionaryOriginsBetweenResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetSharedDictionaryOriginsBetweenParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetSharedDictionaryInfoResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetSharedDictionaryInfoResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetSharedDictionaryInfoResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetSharedDictionaryInfoParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetSharedDictionaryUsageInfoResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetSharedDictionaryUsageInfoResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetSharedDictionaryUsageInfoResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetSharedDictionaryUsageInfoParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextAddReportingApiObserverParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextSetSctAuditingModeParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextForceDomainReliabilityUploadsForTestingResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextForceDomainReliabilityUploadsForTestingResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextForceDomainReliabilityUploadsForTestingResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextForceDomainReliabilityUploadsForTestingParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextAddDomainReliabilityContextForTestingResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextAddDomainReliabilityContextForTestingResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextAddDomainReliabilityContextForTestingResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextAddDomainReliabilityContextForTestingParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextVerifyCertificateForTestingResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextVerifyCertificateForTestingResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextVerifyCertificateForTestingResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextVerifyCertificateForTestingParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextEnableStaticKeyPinningForTestingResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextEnableStaticKeyPinningForTestingResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextEnableStaticKeyPinningForTestingResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextEnableStaticKeyPinningForTestingParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextLookupServerBasicAuthCredentialsResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextLookupServerBasicAuthCredentialsResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextLookupServerBasicAuthCredentialsResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextLookupServerBasicAuthCredentialsParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextSetCorsNonWildcardRequestHeadersSupportParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextAddAuthCacheEntryResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextAddAuthCacheEntryResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextAddAuthCacheEntryResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextAddAuthCacheEntryParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextLoadHttpAuthCacheProxyEntriesResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextLoadHttpAuthCacheProxyEntriesResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextLoadHttpAuthCacheProxyEntriesResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextLoadHttpAuthCacheProxyEntriesParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextSaveHttpAuthCacheProxyEntriesResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextSaveHttpAuthCacheProxyEntriesResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextSaveHttpAuthCacheProxyEntriesResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextSaveHttpAuthCacheProxyEntriesParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextSetSplitAuthCacheByNetworkAnonymizationKeyParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextDeleteDynamicDataForHostResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextDeleteDynamicDataForHostResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextDeleteDynamicDataForHostResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextDeleteDynamicDataForHostParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextSetCorsOriginAccessListsForOriginResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextSetCorsOriginAccessListsForOriginResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextSetCorsOriginAccessListsForOriginResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextSetCorsOriginAccessListsForOriginParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetHstsStateResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetHstsStateResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetHstsStateResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetHstsStateParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextIsHstsActiveForHostResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextIsHstsActiveForHostResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextIsHstsActiveForHostResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextIsHstsActiveForHostParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextAddHstsResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextAddHstsResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextAddHstsResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextAddHstsParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextVerifyCertForSignedExchangeResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextVerifyCertForSignedExchangeResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextVerifyCertForSignedExchangeResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextVerifyCertForSignedExchangeParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextVerifyCertResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextVerifyCertResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextVerifyCertResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextVerifyCertParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCreateHostResolverParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextResolveHostParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCreateMdnsResponderParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCreateP2pSocketManagerParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextPreconnectSocketsParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCreateNetLogExporterParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCreateWebTransportParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCreateWebSocketParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearBadProxiesCacheResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearBadProxiesCacheResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearBadProxiesCacheResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearBadProxiesCacheParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextForceReloadProxyConfigResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextForceReloadProxyConfigResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextForceReloadProxyConfigResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextForceReloadProxyConfigParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextLookUpProxyForUrlParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCreateProxyResolvingSocketFactoryParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCreateTcpBoundSocketResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCreateTcpBoundSocketResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCreateTcpBoundSocketResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCreateTcpBoundSocketParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCreateTcpConnectedSocketResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCreateTcpConnectedSocketResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCreateTcpConnectedSocketResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCreateTcpConnectedSocketParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCreateTcpServerSocketResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCreateTcpServerSocketResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCreateTcpServerSocketResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCreateTcpServerSocketParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCreateRestrictedUdpSocketResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCreateRestrictedUdpSocketResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCreateRestrictedUdpSocketResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCreateRestrictedUdpSocketParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCreateUdpSocketParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextSetCtPolicyParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextSetEnableCrossSiteReferrerStrippingParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextSetEnableReferrersParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextSetAcceptLanguageParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextSetNetworkConditionsParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCloseIdleConnectionsResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCloseIdleConnectionsResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCloseIdleConnectionsResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCloseIdleConnectionsParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCloseAllConnectionsResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCloseAllConnectionsResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCloseAllConnectionsResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCloseAllConnectionsParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextQueueSignedExchangeReportParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextQueueEnterpriseReportParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextQueueReportParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextSendReportsAndRemoveSourceParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextSetEnterpriseReportingEndpointsParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextSetDocumentReportingEndpointsParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearSharedDictionaryCacheForIsolationKeyResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearSharedDictionaryCacheForIsolationKeyResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearSharedDictionaryCacheForIsolationKeyResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearSharedDictionaryCacheForIsolationKeyParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearSharedDictionaryCacheResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearSharedDictionaryCacheResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearSharedDictionaryCacheResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearSharedDictionaryCacheParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearDomainReliabilityResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearDomainReliabilityResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearDomainReliabilityResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearDomainReliabilityParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearNetworkErrorLoggingResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearNetworkErrorLoggingResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearNetworkErrorLoggingResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearNetworkErrorLoggingParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearReportingCacheClientsResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearReportingCacheClientsResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearReportingCacheClientsResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearReportingCacheClientsParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearReportingCacheReportsResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearReportingCacheReportsResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearReportingCacheReportsResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearReportingCacheReportsParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearCorsPreflightCacheResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearCorsPreflightCacheResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearCorsPreflightCacheResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearCorsPreflightCacheParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearHttpAuthCacheResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearHttpAuthCacheResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearHttpAuthCacheResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearHttpAuthCacheParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearHostCacheResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearHostCacheResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearHostCacheResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearHostCacheParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextNotifyExternalCacheHitParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextComputeHttpCacheSizeResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextComputeHttpCacheSizeResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextComputeHttpCacheSizeResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextComputeHttpCacheSizeParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearHttpCacheResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearHttpCacheResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearHttpCacheResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearHttpCacheParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearNetworkingHistoryBetweenResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearNetworkingHistoryBetweenResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearNetworkingHistoryBetweenResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearNetworkingHistoryBetweenParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextSetTrackingProtectionContentSettingParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextSetBlockTrustTokensParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextDeleteStoredTrustTokensResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextDeleteStoredTrustTokensResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextDeleteStoredTrustTokensResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextDeleteStoredTrustTokensParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetPrivateStateTokenRedemptionRecordsResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetPrivateStateTokenRedemptionRecordsResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetPrivateStateTokenRedemptionRecordsResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetPrivateStateTokenRedemptionRecordsParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetStoredTrustTokenCountsResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetStoredTrustTokenCountsResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetStoredTrustTokenCountsResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetStoredTrustTokenCountsParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearTrustTokenSessionOnlyDataResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearTrustTokenSessionOnlyDataResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearTrustTokenSessionOnlyDataResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearTrustTokenSessionOnlyDataParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearTrustTokenDataResponseParamsProxyToResponder;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearTrustTokenDataResponseParamsForwardToCallback;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearTrustTokenDataResponseParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextClearTrustTokenDataParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetTrustTokenQueryAnswererParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetRestrictedCookieManagerParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetCookieManagerParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextGetViaObliviousHttpParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextResetUrlLoaderFactoriesParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextCreateUrlLoaderFactoryParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$NetworkContextSetClientParams;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$Stub;,
        Lorg/chromium/network/mojom/NetworkContext_Internal$Proxy;
    }
.end annotation


# static fields
.field public static final MANAGER:Lorg/chromium/mojo/bindings/Interface$Manager;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Lorg/chromium/mojo/bindings/Interface$Manager<",
            "Lorg/chromium/network/mojom/NetworkContext;",
            "Lorg/chromium/network/mojom/NetworkContext$Proxy;",
            ">;"
        }
    .end annotation
.end field


# direct methods
.method static constructor <clinit>()V
    .locals 1

    new-instance v0, Lorg/chromium/network/mojom/NetworkContext_Internal$1;

    invoke-direct {v0}, Lorg/chromium/network/mojom/NetworkContext_Internal$1;-><init>()V

    sput-object v0, Lorg/chromium/network/mojom/NetworkContext_Internal;->MANAGER:Lorg/chromium/mojo/bindings/Interface$Manager;

    return-void
.end method
