.class public final Lorg/chromium/components/search_engines/SearchEnginesFeatures;
.super Ljava/lang/Object;
.source "SourceFile"


# static fields
.field public static final CLAY_BACKEND_CONNECTION_V2:Ljava/lang/String; = "ClayBackendConnectionV2"

.field public static final CLAY_BLOCKING:Ljava/lang/String; = "ClayBlocking"

.field public static final CLAY_SNACKBAR:Ljava/lang/String; = "ClaySnackbar"

.field public static final DISABLE_SYNC_AUTOGENERATED_SEARCH_ENGINES:Ljava/lang/String; = "DisableSyncAutogeneratedSearchEngines"

.field public static final IOS_PROMPT_SEARCH_ENGINE_CHOICE_AFTER_DEVICE_RESTORE:Ljava/lang/String; = "IOSPromptSearchEngineChoiceAfterDeviceRestore"

.field public static final PREFETCH_PARAMETER_FIX:Ljava/lang/String; = "PrefetchParameterFix"

.field public static final REMOVE_SEARCHBOX_STATS_PARAM_FROM_PREFETCH_REQUESTS:Ljava/lang/String; = "RemoveSearchboxStatsParamFromPrefetchRequests"

.field public static final REMOVE_SEARCH_ENGINE_CHOICE_ATTRIBUTION:Ljava/lang/String; = "RemoveSearchEngineChoiceAttribution"

.field public static final SEARCH_ENGINE_CHOICE_GUEST_EXPERIENCE:Ljava/lang/String; = "SearchEngineChoiceGuestExperience"

.field public static final SEARCH_ENGINE_CHOICE_TRIGGER:Ljava/lang/String; = "SearchEngineChoiceTrigger"


# direct methods
.method public static isEnabled(Ljava/lang/String;)Z
    .locals 0

    invoke-static {p0}, Lorg/chromium/components/search_engines/SearchEnginesFeatureMap;->isEnabled(Ljava/lang/String;)Z

    move-result p0

    return p0
.end method
